feat: Add parseAsStringConst
47ng/nuqs pull request #453
Opened 2024-01-11 09:08 UTC by timheerwagen

Hello, while testing with the package I noticed that there is no support for as const string arrays.

Since I am one of those people who don't like enums, these are better for me to use.

I thought this parser might be interesting for everyone.

I have also extended the documentation and adapted outdated documentation for parseAsStringEnum.

2024-01-11 20:54 UTC, franky47 requested changes
**praise**: That's a good idea, thanks!

I would only suggest using a name that maps directly with TypeScript: literals (see comment).

2024-01-11 20:54 UTC, franky47 commented on packages/nuqs/src/parsers.ts
> +export function parseAsStringConst<Const extends string>(
**suggestion**: The TypeScript name for those is [literal](https://www.typescriptlang.org/docs/handbook/literal-types.html?azure-portal=true), so the parser could be named `parseAsStringLiteral`.

I thought of suggesting dropping the `String` in the name to allow using other literal types like numbers:

```ts
const diceParser = parseAsLiteral([1, 2, 3, 4, 5, 6] as const)
```

But this would require a different type of parsing to convert the query string value into the right type.

I wonder if a generic approach could be done to literal-ify the existing parsers (`parseAsString`, `parseAsInteger`, `parseAsFloat`, `parseAsBoolean` though this last one makes little sense I think).

2024-01-11 20:54 UTC, franky47 commented on packages/nuqs/src/parsers.ts
> + * You will need to pass the parseAsStringEnum function a list of your enum values
**praise** Thanks for catching that one and updating the docs!

2024-01-11 21:13 UTC, timheerwagen commented on packages/nuqs/src/parsers.ts
> +export function parseAsStringConst<Const extends string>(
Thanks for the tip, unfortunately I'm not very familiar with the Typescript names. :)

I have renamed the function and it now accepts string or number literals.

2024-01-11 21:17 UTC, franky47 requested changes

2024-01-11 21:17 UTC, franky47 commented on packages/nuqs/src/parsers.ts
>        if (validValues.includes(asConst)) {
This is what I meant by having to extend the existing numeric parsers: using number literals here won't work as the array [1, 2, 3] never contains the value "2", it has to be parsed first.

We could hack our way out by detecting if the first element of the validValues is a number, then pass it through `parseFloat`, which handles all cases for numeric literals.

2024-01-11 22:06 UTC, timheerwagen commented on packages/nuqs/src/parsers.ts
>        if (validValues.includes(asConst)) {
Maybe it would be enough to provide 2 functions, that looks too much like a hack to me? `parseAsStringLiteral` and `parseAsNumberLiteral`

2024-01-11 22:35 UTC, franky47 commented on packages/nuqs/src/parsers.ts
>        if (validValues.includes(asConst)) {
Sounds like a good plan indeed.

2024-01-12 12:21 UTC, timheerwagen commented on packages/nuqs/src/parsers.ts
>        if (validValues.includes(asConst)) {
Please take a look at this.

By the way, I can't think of any other uses for literals in query than String and Number. So a generic attempt would not really achieve much. You can always create your own parser for special use-cases.

2024-01-12 12:24 UTC, franky47 requested changes
Last little change on the docs and it looks great.

2024-01-12 12:24 UTC, franky47 commented on README.md
>      .withDefault('red')
**suggestion**: Update the doc to include a valid default value, like 4: https://xkcd.com/221/

2024-01-12 12:24 UTC, franky47 commented on packages/nuqs/src/parsers.ts
>        if (validValues.includes(asConst)) {
The only other allowed literal type is boolean, and we already have a parser for that one, so this is perfect, thanks!

2024-01-12 12:33 UTC, timheerwagen commented on README.md
>      .withDefault('red')
Oops, I must have overlooked that.

2024-01-12 13:58 UTC, franky47 approved these changes

2024-01-12 23:23 UTC, merged