Fix/serialization default values
47ng/nuqs pull request #642
Opened 2024-09-19 07:49 UTC by hugotiger

2024-09-19 09:21 UTC, franky47 commented
Thanks! Could you change back the base branch to next for this one? It's not a breaking change, so it can be published on the v1 release line.

I pushed a fix for the types to let parsers know they can have a default value.

2024-09-20 11:41 UTC, franky47 requested changes
One test is failing, see https://github.com/47ng/nuqs/actions/runs/10936702232/job/30378534527#step:7:90

2024-09-21 13:48 UTC, hugotiger commented
> One test is failing, see https://github.com/47ng/nuqs/actions/runs/10936702232/job/30378534527#step:7:90

I'm not able to reproduce it locally 🤔 Could it be some caching issue in the action? For context when I run `pnpm run test` it's all green.

2024-09-23 12:57 UTC, hugotiger commented
> > One test is failing, see https://github.com/47ng/nuqs/actions/runs/10936702232/job/30378534527#step:7:90
> 
> I'm not able to reproduce it locally 🤔 Could it be some caching issue in the action? For context when I run `pnpm run test` it's all green.

I checked again now and it seems as if the CI was running on some previous commit. Could you do a rerun?

2024-09-23 15:04 UTC, franky47 approved these changes

2024-09-23 15:22 UTC, merged

2024-09-23 15:22 UTC, franky47 commented
Thanks!