Refactor: Split pkg.pr.new into distinct check and deploy jobs
47ng/nuqs pull request #659
Opened 2024-09-27 16:07 UTC by chbg

### Overview
This pull request refactors the CI workflow by separating the process into two jobs: one for checking changes in the nuqs package and another for the deployment process. This change optimizes the workflow by ensuring that the deployment job is only executed when there are actual changes to the package, preventing unnecessary builds and enhancing overall efficiency.

### Changes Made

- Created a new job (check-changes) to detect modifications in the nuqs package.
- The deployment job (deploy-preview) now only runs if changes are detected, improving the efficiency of the CI pipeline.
- Conditional logic was added to manage the flow between the two jobs based on the output from the change detection job.

### Benefits

- Reduces unnecessary build processes when no changes are present.
- Improves clarity and maintainability of the workflow configuration.
- Enhances the overall performance of the CI process.

2024-09-27 16:18 UTC, franky47 commented
> 
> [Open in Stackblitz](https://pkg.pr.new/template/6270eccb-5fdc-422a-84b7-2815578418ae)
> 
> 
> ```
> pnpm add https://pkg.pr.new/nuqs@659
> ```
> 
> 
> _commit: <a href="https://github.com/47ng/nuqs/runs/30771773925"><code>f5d11c6</code></a>_
> 

Damn, something's wrong then 😅

2024-09-27 16:24 UTC, chbg commented
> > [Open in Stackblitz](https://pkg.pr.new/template/6270eccb-5fdc-422a-84b7-2815578418ae)
> > ```
> > pnpm add https://pkg.pr.new/nuqs@659
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _commit: [`f5d11c6`](https://github.com/47ng/nuqs/runs/30771773925)_
> 
> Damn, something's wrong then 😅

Oops, I see what I did. Fixing...

2024-09-27 17:04 UTC, franky47 commented
This might help:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs

Also, the if check on the deployment job should use a == to make sure only a valid value enables it (a != will trigger on an empty value). Might need to inverse the logic name (enable rather than skip), to make it clearer.

2024-09-27 17:08 UTC, chbg commented
> This might help: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs
> 
> Also, the if check on the deployment job should use a == to make sure only a valid value enables it (`skip != 'true'` will trigger on an empty value). Might need to inverse the logic name (enable rather than skip), to make it clearer.

I will check that article out shortly. Also, thanks for the input on the deployment job. Stepping away for a little, but will work to resolve this today!

2024-09-27 19:25 UTC, chbg commented on .github/workflows/pkg.pr.new.yml
> -    if: github.event.review.state == 'APPROVED' || contains(github.event.pull_request.author_association, 'MEMBER')
> General logic looks good, but can we keep this condition on the check job? It only allows deployment if the PR is approved, or if it's from a core maintainer.
> 
> If the check job is skipped, the deployment job will not run either.

I'll submit a new commit shortly with this in place.

2024-09-27 19:35 UTC, chbg commented
@franky47 , new commit ready for review.

2024-09-27 20:48 UTC, franky47 requested changes
Maybe my suggestion wasn't clear. I meant keeping the approved || member condition on the first job. If that's allowed to run, we run the Git check, then the second job can start if enabled.

If you're using the GitHub web UI, feel free to use the "Add to batch" feature to pool all those suggestions in a single commit.

2024-09-27 20:48 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
> +          fetch-depth: 2
We can remove the fetch depth on this job, having only the last commit will do.
```suggestion
```

2024-09-27 20:48 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
> +          if [[ "${{ github.event.review.state }}" != "APPROVED" && ! "$(echo "${{ github.event.pull_request.author_association }}" | grep 'MEMBER')" ]]; then
Restore the Git check

```suggestion
          if git diff --quiet HEAD^ HEAD ./packages/nuqs; then
```

2024-09-27 20:48 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
> +      - name: Check for PR Approval
```suggestion
      - name: Check for relevant changes
```

2024-09-27 20:48 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
> +  check-changes:
Restore workflow authorization check

```suggestion
  check-changes:
    name: Check for relevant changes to deploy
    if: github.event.review.state == 'APPROVED' || contains(github.event.pull_request.author_association, 'MEMBER')
```

2024-09-27 20:48 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
> +            echo "enable=true" >> $GITHUB_OUTPUT
```suggestion
            echo "No changes to nuqs package, skipping preview deployment."
            echo "enable=false" >> $GITHUB_OUTPUT
          else
            echo "enable=true" >> $GITHUB_OUTPUT
```

2024-09-27 20:48 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
>          run: pnpm build --filter nuqs
Remove blank lines

```suggestion
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build --filter nuqs
```

2024-09-27 20:48 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
> +
Restore the package version set step

```suggestion
      - name: Set package version
        run: pnpm pkg set version=0.0.0-preview.${{ github.event.pull_request.head.sha }}
        working-directory: packages/nuqs
```

2024-09-29 05:13 UTC, franky47 requested changes
The overall split looks better, but now we need to fix the passing of the `enable` flag between the two jobs, by setting a job-level output in the check job, and consuming it in the deploy job.

Docs showcasing this: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs#example-defining-outputs-for-a-job

1. Add back an ID for the step doing the Git check (so we can use it to map the step output to a job output)
2. Declare and connect a job output for the check job
3. Re-connect the two jobs with `need` (see suggestion)
4. Update the if clause for the deploy job to use the job-level output we defined earlier

2024-09-29 05:13 UTC, franky47 commented on .github/workflows/pkg.pr.new.yml
> +    if: needs.check-changes.outputs.enable == 'true'
We need to connect the two jobs again:
```suggestion
    if: needs.check-changes.outputs.enable == 'true'
    needs: check-changes
```

2024-09-29 21:12 UTC, chbg commented
> The overall split looks better, but now we need to fix the passing of the `enable` flag between the two jobs, by setting a job-level output in the check job, and consuming it in the deploy job.
> 
> Docs showcasing this: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs#example-defining-outputs-for-a-job
> 
> 1. Add back an ID for the step doing the Git check (so we can use it to map the step output to a job output)
> 2. Declare and connect a job output for the check job
> 3. Re-connect the two jobs with `need` (see suggestion)
> 4. Update the if clause for the deploy job to use the job-level output we defined earlier

Ok, great. I will work on getting these in place in the next 12 - 24 hours.

2024-10-01 05:20 UTC, chbg commented
@franky47 , I think this should do it. I've also updated the original PR description to reflect the changes made to date vs. the original file.

2024-10-01 07:29 UTC, franky47 approved these changes
LGTM, thank you!

2024-10-01 07:57 UTC, franky47 commented
I also have added a way to trigger this on labelled PRs, to bypass the approval mechanism (sometimes it might be handy). Thanks for your help!

2024-10-01 07:57 UTC, merged