feat: Add parseAsISODate
47ng/nuqs pull request #707
Opened 2024-10-25 05:45 UTC by tylersayshi

follow up to https://github.com/47ng/nuqs/discussions/705

2024-10-25 08:39 UTC, franky47 commented on packages/docs/content/docs/parsers/built-in.mdx
> +
**suggestion**: Should we add a disclaimer that the returned Date object is rooted in UTC ?

2024-10-25 08:41 UTC, franky47 commented on packages/docs/content/docs/parsers/demos.tsx
> +  return <DateParserDemo queryKey="iso" parser={parseAsIsoDate} />
**suggestion**: The input inside the `<DateParserDemo>` component is currently harcoded to `type="datetime-local"`. For this parser, we're not interested in the time, so a `type="date"` would make more sense. We could add a prop to `DateParserDemo` to do that.

Also, binding to the same queryKey will cause issues, see the caveats section of the docs:
https://nuqs.47ng.com/docs/troubleshooting#caveats

2024-10-25 08:44 UTC, franky47 commented on packages/nuqs/src/parsers.test.ts
> +    expect(parseAsIsoDate.serialize(ref).length).not.toContain('T')
suggestion: We could check for equality with the expected format here.

```suggestion
    expect(parseAsIsoDate.serialize(ref)).toEqual(moment)
```

2024-10-25 08:52 UTC, franky47 commented on packages/nuqs/src/parsers.ts
> +    const date = new Date(v + 'T00:00:00.000Z')
**suggestion**: Clip the input to 10 chars to remove time information from full dates. Eg:

`?date=2020-01-01T12:34:56.789Z` -> `?date=2020-01-01T00:00:00.000Z` rather than an invalid date.

```suggestion
    const date = new Date(v.slice(0, 10) + 'T00:00:00.000Z')
```

Do we need to append the time information? `new Date('2020-01-01')` already returns the correct UTC value of midnight for that day (tested in Firefox and Node.js)

2024-10-25 22:11 UTC, tylersayshi commented on packages/docs/content/docs/parsers/built-in.mdx
> +
Good call! Disclaimer added to the jsdoc and the docs here 👍

2024-10-25 22:12 UTC, tylersayshi commented on packages/docs/content/docs/parsers/demos.tsx
> +  return <DateParserDemo queryKey="iso" parser={parseAsIsoDate} />
nice! fixed both. Thanks for calling out the queryKey, that was just an oversight while copy-pasteing the existing docs.

2024-10-25 22:13 UTC, tylersayshi commented on packages/nuqs/src/parsers.test.ts
> +    expect(parseAsIsoDate.serialize(ref).length).not.toContain('T')
nice, yeah this cleans up and is more comprehensive a test. Thanks

2024-10-25 22:14 UTC, tylersayshi commented on packages/nuqs/src/parsers.ts
> +    const date = new Date(v + 'T00:00:00.000Z')
I think I just misread a timestamp while building this initially. I just tested the same and got the same result. 

Fixed to remove the extra `'T00:00:00.000Z'`

2024-10-25 22:24 UTC, franky47 requested changes
Thanks! I'd rather keep the `iso` query key for the datetime parser to avoid potential URL breakage.

I forgot I had Prettier disabled for MDX locally, I'll have to put that in the config. Not a big deal, we'll see if it creates formatting issues with the preview deployment.

2024-10-25 22:24 UTC, franky47 commented on packages/docs/content/docs/parsers/demos.tsx
> -  return <DateParserDemo queryKey="iso" parser={parseAsIsoDateTime} />
**suggestion**: Can we keep the `iso` key here? In order not to break existing URLs (I doubt many people would have linked to the parsers demos, but it's always a good exercise).

We could have:
- `iso`: full ISO-8601 (date + time)
- `date`: just the first 10 characters (date string)
- `ts`: unix timestamp ms

2024-10-25 22:24 UTC, franky47 commented on packages/nuqs/src/parsers.ts
> + * making it at GMT 00:00:00 UTC.
**nitpick**: Can't be both GMT & UTC (even though they are equal in our case)

```suggestion
 * making it at 00:00:00 UTC.
```

2024-10-25 23:06 UTC, tylersayshi commented
> I forgot I had Prettier disabled for MDX locally, I'll have to put that in the config. Not a big deal, we'll see if it creates formatting issues with the preview deployment.

I had been formatting without save before then accidentally let it format. Would you like me to revert that?

2024-10-26 02:43 UTC, franky47 approved these changes
LGTM, thanks Tyler!

2024-10-26 06:44 UTC, merged

2024-10-30 19:24 UTC, franky47 commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/nuqs/v/2.1.0)
- [GitHub release](https://github.com/47ng/nuqs/releases/tag/v2.1.0)