Log an error in development if URI size of 2000 characters is exceeded.
47ng/nuqs pull request #747
Opened 2024-11-06 22:55 UTC by niklasbec

As discussed [here](https://github.com/47ng/nuqs/pull/739#pullrequestreview-2416727212), error logging for when a user stores more than 2000 characters of state in a URI.

2024-11-06 22:58 UTC, niklasbec commented
@franky47 wasn't to sure about the placement of the log, let me know.

2024-11-08 13:56 UTC, franky47 requested changes
Thanks! 

One global thing to change in addition to individual suggestions is the term URL rather than URI, to be consistent with the rest of the codebase (URLSearchParams, window.location etc).

2024-11-08 22:22 UTC, niklasbec commented on packages/nuqs/src/update-queue.ts
> +      if (URIIsTooLong() && process.env.NODE_ENV === 'development') {
I know that Bun is designed with Node.js in mind so they expose the node env over process.env just like node does. AFAIK deno doesn't support this.

It works for vite and most other bundlers use plugins to expose process.env aswell.

2024-11-08 22:23 UTC, niklasbec commented on packages/nuqs/src/update-queue.ts
> +      if (URIIsTooLong() && process.env.NODE_ENV === 'development') {
We can remove the second check but then you would have to warnings in prod builds.

2024-11-10 23:12 UTC, niklasbec commented
@franky47 I refactored according to your remarks, please have a look if this works for you.

2024-11-11 09:46 UTC, franky47 approved these changes

2024-11-12 13:44 UTC, merged