feat: Added react-router v7 support
47ng/nuqs pull request #785
Opened 2024-11-28 05:21 UTC by teukuamru

Added support for react-router v7 ( Closes #782 )

2024-11-28 05:27 UTC, franky47 requested changes
LGTM, thanks!

Maybe we could add a comment in the `adapters/react-router` adapter mentioning it's for v6.

Also an update of the docs would be welcome, to point folks to the right adapter (using Callouts in the Remix section).

2024-11-28 05:27 UTC, franky47 commented on packages/nuqs/adapters/react-router/v6.d.ts
> +// in their tsconfig.json to be able to `import {} from 'nuqs/adapters/react-router'`.
**suggestoion**: could you update the comment path here too please? So it's easier to find & replace all references.

2024-11-30 18:04 UTC, rickyzhangca commented
can't wait!

2024-12-05 20:45 UTC, fobos531 commented
@franky47 Is there anything blocking this?

@teukuamru I see that the lint action failed - seems pretty easy to fix, the `peerDependencies` just need to be sorted

2024-12-05 20:54 UTC, franky47 commented
I need to find some free time to try out RRv7, I had an unpushed branch with Remix improvements that could also be factored in this.

2024-12-06 04:29 UTC, teukuamru commented
> I need to find some free time to try out RRv7, I had an unpushed branch with Remix improvements that could also be factored in this.

so, should I fix the lint or just wait for you to try out RRv7?

2024-12-08 19:03 UTC, franky47 commented
I'll do it, I'm also going to add e2e tests for Remix, RRv6 & RRv7.

2024-12-10 08:56 UTC, franky47 approved these changes

2024-12-10 09:27 UTC, merged

2024-12-10 09:29 UTC, franky47 commented
Merged but I want to add some more tests in a separate PR before shipping it to GA. In the mean time, y'all can use the preview deployment (feedback welcome!):

```
pnpm add https://pkg.pr.new/nuqs@785
```

And import the adapter as such:
```
// app/root.tsx
import { NuqsAdapter } from 'nuqs/adapters/react-router/v7'

// ...

export default function App() {
  return (
    <NuqsAdapter>
      <Outlet />
    </NuqsAdapter>
  )
}
```

2024-12-10 09:49 UTC, franky47 commented
@faradaytrs Try that URL: `https://pkg.pr.new/nuqs@d000ca8db65a027e11960c4b99736017c2a5ddaa`

I'll check with the pkg.pr.new folks what went wrong with the PR-numbered release, thanks for the heads-up.

2024-12-10 10:46 UTC, faradaytrs commented
> @faradaytrs Try that URL: `https://pkg.pr.new/nuqs@d000ca8db65a027e11960c4b99736017c2a5ddaa`
> 
> I'll check with the pkg.pr.new folks what went wrong with the PR-numbered release, thanks for the heads-up.

i upgraded and it works fine, no problems detected

2024-12-28 22:07 UTC, ZipBrandon commented
I'm using 2.3.0-beta.2 on a new RR7 app. I incorporated the adapter with `import { NuqsAdapter } from 'nuqs/adapters/react-router/v7'`, but when I use `useQueryState()` I get `Error: useNavigate() may be used only in the context of a <Router> component.`.  I have the Adapter surrounding the outlet in the App.

```tsx
export default function App() {
	return (
		<NuqsAdapter>
			<Outlet />
		</NuqsAdapter>
	);
}```

2024-12-29 06:27 UTC, franky47 commented
@ZipBrandon thanks for the feedback and testing the beta!

Could you open a dedicated issue with a repro link so I can take a look please?